### ISSUE TITLE
Setting a too-high duration for `watering.pause_all` returns an `HTTP 401`

### ISSUE THREAD

**Issue by cmerritt82** [bachya/regenmaschine#101]
When trying to run a home assistant animation, I am getting an error stating "long lived token has expired".  This causes the animation to fail.  The animation is based off of two binary sensors setup to pause and resume watering based on the sensor state of the other.  In a sense, I am trying to tell one controller to pause its programming until the other controller has finished its program.

To reproduce, below is the animation I have setup.

```yaml
id: '1626385140990'
alias: Irrigation Sequencing Pause
description: Start Secondary Controller After Primary
trigger:
  - platform: state
    entity_id: binary_sensor.controller_b_running
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: binary_sensor.controller_a_running
    state: 'on'
action:
  - service: rainmachine.pause_watering
    data:
      seconds: 86400
    target:
      entity_id:
        - switch.back_yard
mode: single
```

**Expected behavior**
I expected the animation to fire as is with no long lived tokenerrors.  

**Screenshots**
![Capture](https://user-images.githubusercontent.com/76022945/129092803-2f70df44-aa19-4341-9e20-f1471657ca04.JPG)

**Desktop (please complete the following information):**
 - OS: Synology DSM 6.X running HA Core Docker Container
 - Browser: Microsoft Edge
 - Version: core-2021.8.5

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: 14.7.1
 - Browser Microsoft Edge for iOS
 - Version 14.7.1

**Additional context**
Happy to assist in any way I can to fix. Thanks!

**Comment by bachya** [comment]
@cmerritt82 Thanks for following up! In your Home Assistant, please set the RainMachine-specific logs to `DEBUG`-level:

```
logger:
  default: info
  logs:
    homeassistant.components.rainmachine: debug
    regenmaschine: debug
```

...and restart your Home Assistant. Run your automation again and then shut down Home Assistant. Copy/paste any logs related to `homeassistant.components.rainmachine` or `regenmaschine` here.

Thanks!
